### ISSUE TITLE
Timezone in webpage

### ISSUE THREAD

**Issue by tomamdy** [jekhokie/raspberry-noaa-v2#156]
Can get the correct time for Amsterdam in the webpanel, but it still gives America/New York

![2021-02-19 15_50_23-Raspberry NOAA V2](https://user-images.githubusercontent.com/67389269/108520419-f2f47780-72ca-11eb-809a-a67bf31ab08c.png)

# locale settings for timezone and language
#   timezone: see https://www.php.net/manual/en/timezones.php
#   lang_setting: see the 'webpanel/App/Lang' folder for available
#                 languages (2-letter filename - e.g. ar, bg, de, en, es, nl, sr)
timezone:Europe/Amsterdam
lang_setting: en

**Comment by jekhokie** [comment]
@tomamdy did you re-run the install_and_upgrade.sh script after making the config change? What does the file /var/www/wx-new/Config/Config.php have for the locale? If it’s still America/New York, it likely means you updated the settings.yml file but haven’t yet re-run the install script since making the change to have the config pushed to all locations.

**Comment by tomamdy** [comment]
It is very strange. With the Raspberry 4 it gives not a problem, but it only happened with the 3B.
Now I changed by hand /var/www/wx-new/Config/Config.php the locale and it is ok now.
