### ISSUE TITLE
Better Job Conflict Handling

### ISSUE THREAD

**Issue by jekhokie** [jekhokie/raspberry-noaa-v2#163]
Right now, the NOAA receive script yields to Meteor captures, but only if Meteor is using rtl_fm. This functionality needs to be expanded to include gnuradio now that Meteor can use this method, and this might possibly be an opportunity to create better job handling logic since even if a Meteor signal receive is complete, if processing is occurring (demodulation, decoding, etc.), it's possible that the Meteor processing at the same time as NOAA capture might cause overload of the Pi, forcing a reboot and destroying both captures.

**Comment by dom-robinson** [comment]
I think @jekhokie resolved this by allowing multiple devices to be selected in the settings. Closing this for now since without a complete refactor of how the capture process works (to potentially constantly record the entire 137mhz frequency and extract audio from the wideband capture) the multidevice option seems to be the only way.

Closing for now, but happy to reopen if i missed something..
