### ISSUE TITLE
Meteor M2 not show

### ISSUE THREAD

**Issue by wifi75** [jekhokie/raspberry-noaa-v2#535]
Hello on my passes list meteror m2 is present.
after the passage even after a few hours I do not see any image of the passage of meteor m2, the tab does not even appear, yet in the configuration it is enabled.

why?

**Comment by dom-robinson** [comment]
does the output.log not detail what is happening?

**Comment by wifi75** [comment]
I am attaching my log, I am not able to understand ...
[output.log](https://github.com/jekhokie/raspberry-noaa-v2/files/8570901/output.log)

**Comment by guidocioni** [comment]
Been seeing the same issue today.
I usually get always a METEOR M2 image but since today I'm not able to get any results.

The recording seems fine (according to the spectogram) 
![METEOR-M-2-20220506-165648-spectrogram](https://user-images.githubusercontent.com/12760310/167186291-ddb1399c-2aeb-461f-8598-1b0f48b61893.png)

but then in the decoding it doesn't seem to find any valid package, as in @wifi75. May be the same issue

**Comment by guidocioni** [comment]
Apparently METEOR M2 has been having some positional issues and the VHF stream has been disabled since 4 May. 
This is the reason behind the missing images.

**Comment by dom-robinson** [comment]
This this was satellite side - closing this now
