### ISSUE TITLE
Issue with accessing database after installing [Error]

### ISSUE THREAD

**Issue by chr0nik** [jekhokie/raspberry-noaa-v2#911]
Hi,

After successfully install raspberry-noaa-v2 on a Orange PC mini computer running Armbian, I get the following issue:

Fatal error: Uncaught Exception: Unable to open database: unable to open database file in /var/www/wx-new/Lib/Controller.php:46 Stack trace: #0 /var/www/wx-new/Lib/Controller.php(46): SQLite3->__construct() #1 /var/www/wx-new/Lib/Controller.php(12): Lib\Controller->connectToDB() #2 /var/www/wx-new/Lib/Router.php(50): Lib\Controller->__construct() #3 /var/www/wx-new/Lib/Router.php(13): Lib\Router->handleRequest() #4 /var/www/wx-new/public/index.php(16): Lib\Router->__construct() #5 {main} thrown in /var/www/wx-new/Lib/Controller.php on line 46

Can anybody please assist, thanks!

**Comment by MihajloPi** [comment]
Please try updating your OS and update RN2 to the latest version and run the install script to see if it solves the issue.

**Comment by jtadesse977** [comment]
Getting same issue, have been digging around var/www/wx-new/Lib with no luck. Also did full update as well. The database exists because i can use sqlite3 commands on db file but for some reason has issue with line 46: $this->db_conn = new \SQLite3(Config::DB_FILE); I have tried removing Config::DB_FILE and put the literal db path but i get same error as above. Maybe an access/ownership issue?

**Comment by jtadesse977** [comment]
YO I FIGURE IT OUT

**Comment by jtadesse977** [comment]
Your /home/user directory doesn't have the write/read permissions. If you want to just say screw it you can chmod 777 the directories from /home all the way to the /db directory. That way your /var/www directory has access to the database. Once you do that it should work but if not lmk. Also you can change it back and give it the proper permissions but this is just to test if permissions is the issue for you.
