### ISSUE TITLE
Rádiosondes 

### ISSUE THREAD

**Issue by OK1SLM** [jekhokie/raspberry-noaa-v2#914]
It would be interesting to run a script for monitoring radiosondes in free moments.
https://github.com/projecthorus/radiosonde_auto_rx/wiki

**Comment by MihajloPi** [comment]
Radiosondes transmit in the 70 cm band, while our satellites transmit in the 2 m band. Antennas for satellites aren't good at receiving radiosondes since they aren't tuned for them + many receiving stations have filters installed only allowing 137 MHz from the satellites, while blocking everything else including the radiosondes. While certainly interesting, it wouldn't be effective, and this project is mainly geared towards the satellite reception.
